### ISSUE TITLE
How to install this plugin from Web UI?

### ISSUE THREAD

**Issue by pke** [jenkinsci/npm-yarn-wrapper-steps-plugin#9]
I wonder how do I install this plugin into Jenkins using the Web UI?

**Comment by jameslafferty** [comment]
@pke Which version of Jenkins are you using? If it's a compatible version (>=2.263.4), it should show up under `/pluginManager/available`. Here's how I navigate there:
<img width="1041" alt="Screen Shot 2021-10-13 at 2 42 46 PM" src="https://user-images.githubusercontent.com/1176300/137216655-1de0f9c5-7712-4069-840c-8926c84e0ef9.png">

**Comment by jameslafferty** [comment]
Please feel free to reopen/reach out again if the above doesn't answer your question.

**Comment by pke** [comment]
Seems my jenkins is too old :) Thanks for your reply
